// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DatabaseReplication module
	public static void aCr_CustomConstraint(IContext context, databasereplication.proxies.CustomConstraint _customConstraint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CustomConstraint", _customConstraint == null ? null : _customConstraint.getMendixObject());
		Core.microflowCall("DatabaseReplication.ACr_CustomConstraint").withParams(params).execute(context);
	}
	public static void aCr_Database(IContext context, databasereplication.proxies.Database _database)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Database", _database == null ? null : _database.getMendixObject());
		Core.microflowCall("DatabaseReplication.ACr_Database").withParams(params).execute(context);
	}
	public static boolean aSu_CheckModelAndMapping(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.ASu_CheckModelAndMapping").withParams(params).execute(context);
	}
	public static boolean bCo_AdditionalJoins(IContext context, databasereplication.proxies.AdditionalJoins _additionalJoins)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AdditionalJoins", _additionalJoins == null ? null : _additionalJoins.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BCo_AdditionalJoins").withParams(params).execute(context);
	}
	public static boolean bCo_ColumnMapping(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BCo_ColumnMapping").withParams(params).execute(context);
	}
	public static boolean bCo_Constraint(IContext context, databasereplication.proxies.Constraint _constraint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Constraint", _constraint == null ? null : _constraint.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BCo_Constraint").withParams(params).execute(context);
	}
	public static boolean bCo_CustomConstraint(IContext context, databasereplication.proxies.CustomConstraint _customConstraint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CustomConstraint", _customConstraint == null ? null : _customConstraint.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BCo_CustomConstraint").withParams(params).execute(context);
	}
	public static boolean bCo_Database(IContext context, databasereplication.proxies.Database _database)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Database", _database == null ? null : _database.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BCo_Database").withParams(params).execute(context);
	}
	public static boolean bCo_TableMapping(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BCo_TableMapping").withParams(params).execute(context);
	}
	public static boolean bDe_ColumnMapping(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BDe_ColumnMapping").withParams(params).execute(context);
	}
	public static boolean bRb_AdditionalJoins(IContext context, databasereplication.proxies.AdditionalJoins _additionalJoins)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AdditionalJoins", _additionalJoins == null ? null : _additionalJoins.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BRb_AdditionalJoins").withParams(params).execute(context);
	}
	public static boolean bRb_ColumnMapping(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BRb_ColumnMapping").withParams(params).execute(context);
	}
	public static boolean bRb_Constraint(IContext context, databasereplication.proxies.Constraint _constraint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Constraint", _constraint == null ? null : _constraint.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.BRb_Constraint").withParams(params).execute(context);
	}
	public static java.lang.String cA_GetMappingTitle(IContext context, databasereplication.proxies.UpdateConfiguration _updateConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UpdateConfiguration", _updateConfiguration == null ? null : _updateConfiguration.getMendixObject());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.CA_GetMappingTitle").withParams(params).execute(context);
	}
	public static boolean cA_ShouldShowCustomQuery(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.CA_ShouldShowCustomQuery").withParams(params).execute(context);
	}
	public static boolean cA_ShouldShowSelectStatement(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.CA_ShouldShowSelectStatement").withParams(params).execute(context);
	}
	public static void ch_FindAttribute(IContext context, databasereplication.proxies.ColumnMapping _columnmapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("columnmapping", _columnmapping == null ? null : _columnmapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.Ch_FindAttribute").withParams(params).execute(context);
	}
	public static void ch_FindObjectType(IContext context, databasereplication.proxies.ColumnMapping _columnmapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("columnmapping", _columnmapping == null ? null : _columnmapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.Ch_FindObjectType").withParams(params).execute(context);
	}
	public static void ch_FindReference(IContext context, databasereplication.proxies.ColumnMapping _columnmapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("columnmapping", _columnmapping == null ? null : _columnmapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.Ch_FindReference").withParams(params).execute(context);
	}
	public static void ch_RefreshCM(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.Ch_RefreshCM").withParams(params).execute(context);
	}
	public static void ch_SetAttribute(IContext context, databasereplication.proxies.ColumnMapping _columnmapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("columnmapping", _columnmapping == null ? null : _columnmapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.Ch_SetAttribute").withParams(params).execute(context);
	}
	public static void ch_SetObjectTypeReference(IContext context, databasereplication.proxies.ColumnMapping _columnmapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("columnmapping", _columnmapping == null ? null : _columnmapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.Ch_SetObjectTypeReference").withParams(params).execute(context);
	}
	public static void ch_SetReference(IContext context, databasereplication.proxies.ColumnMapping _columnmapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("columnmapping", _columnmapping == null ? null : _columnmapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.Ch_SetReference").withParams(params).execute(context);
	}
	public static void cH_UpdateConnectionExample(IContext context, databasereplication.proxies.CustomConnectionInfo _customConnectionInfo)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CustomConnectionInfo", _customConnectionInfo == null ? null : _customConnectionInfo.getMendixObject());
		Core.microflowCall("DatabaseReplication.CH_UpdateConnectionExample").withParams(params).execute(context);
	}
	public static java.lang.String checkEmptyString(IContext context, java.lang.String _inputString)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("inputString", _inputString);
		return (java.lang.String) Core.microflowCall("DatabaseReplication.CheckEmptyString").withParams(params).execute(context);
	}
	public static void column_SetCorrectRefObjectType(IContext context, mxmodelreflection.proxies.MxObjectReference _reference, databasereplication.proxies.ColumnMapping _columnMapping, mxmodelreflection.proxies.MxObjectType _startMxObjectType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Reference", _reference == null ? null : _reference.getMendixObject());
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		params.put("StartMxObjectType", _startMxObjectType == null ? null : _startMxObjectType.getMendixObject());
		Core.microflowCall("DatabaseReplication.Column_SetCorrectRefObjectType").withParams(params).execute(context);
	}
	public static java.util.List<databasereplication.proxies.TableMapping> importXMLFile(IContext context, databasereplication.proxies.XMLDocumentTM _xMLDocument, databasereplication.proxies.Database _selectedDatabase)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("XMLDocument", _xMLDocument == null ? null : _xMLDocument.getMendixObject());
		params.put("SelectedDatabase", _selectedDatabase == null ? null : _selectedDatabase.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DatabaseReplication.ImportXMLFile").withParams(params).execute(context);
		java.util.List<databasereplication.proxies.TableMapping> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(databasereplication.proxies.TableMapping.initialize(context, obj));
		}
		return result;
	}
	public static void iVK_AbortAllRunningImports(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseReplication.IVK_AbortAllRunningImports").withParams(params).execute(context);
	}
	public static void iVK_AbortSelectedRunningImport(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_AbortSelectedRunningImport").withParams(params).execute(context);
	}
	public static void iVK_CancelImportCall(IContext context, databasereplication.proxies.ImportCall _importCall)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportCall", _importCall == null ? null : _importCall.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_CancelImportCall").withParams(params).execute(context);
	}
	public static void iVK_ColMapping_SaveClose(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ColMapping_SaveClose").withParams(params).execute(context);
	}
	public static void iVK_ColMapping_SaveNext(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ColMapping_SaveNext").withParams(params).execute(context);
	}
	public static void iVK_CustomConstraint_Save(IContext context, databasereplication.proxies.CustomConstraint _customConstraint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CustomConstraint", _customConstraint == null ? null : _customConstraint.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_CustomConstraint_Save").withParams(params).execute(context);
	}
	public static void iVK_ExportAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseReplication.IVK_ExportAll").withParams(params).execute(context);
	}
	public static void iVK_ExportMappingList(IContext context, java.util.List<databasereplication.proxies.TableMapping> _tableMappingList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_tableMappingList = null;
		if (_tableMappingList != null)
		{
			listparam_tableMappingList = new java.util.ArrayList<>();
			for (databasereplication.proxies.TableMapping obj : _tableMappingList)
				listparam_tableMappingList.add(obj.getMendixObject());
		}
		params.put("TableMappingList", listparam_tableMappingList);

		Core.microflowCall("DatabaseReplication.IVK_ExportMappingList").withParams(params).execute(context);
	}
	public static void iVK_GetAllTableInfo(IContext context, databasereplication.proxies.Database _database)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Database", _database == null ? null : _database.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_GetAllTableInfo").withParams(params).execute(context);
	}
	public static void iVK_ImportByImportCallConfig(IContext context, databasereplication.proxies.ImportCall _importCall)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportCall", _importCall == null ? null : _importCall.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ImportByImportCallConfig").withParams(params).execute(context);
	}
	public static void iVK_ImportTableMapping(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ImportTableMapping").withParams(params).execute(context);
	}
	public static void iVK_ImportXML_Upload(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseReplication.IVK_ImportXML_Upload").withParams(params).execute(context);
	}
	public static void iVK_NewColumn(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_NewColumn").withParams(params).execute(context);
	}
	public static void iVK_NewConstraint(IContext context, databasereplication.proxies.AdditionalJoins _additionalJoin)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AdditionalJoin", _additionalJoin == null ? null : _additionalJoin.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_NewConstraint").withParams(params).execute(context);
	}
	public static void iVK_NewJoin(IContext context, databasereplication.proxies.TableMapping _mapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Mapping", _mapping == null ? null : _mapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_NewJoin").withParams(params).execute(context);
	}
	public static void iVK_RemoveAllConfigItems(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseReplication.IVK_RemoveAllConfigItems").withParams(params).execute(context);
	}
	public static void iVK_ReselectObjectType(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ReselectObjectType").withParams(params).execute(context);
	}
	public static void iVK_ReselectObjectTypeFinal(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ReselectObjectTypeFinal").withParams(params).execute(context);
	}
	public static void iVK_SaveDatabaseInfo(IContext context, databasereplication.proxies.Database _database)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Database", _database == null ? null : _database.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_SaveDatabaseInfo").withParams(params).execute(context);
	}
	public static void iVK_SaveImportCall(IContext context, databasereplication.proxies.ImportCall _importCall)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportCall", _importCall == null ? null : _importCall.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_SaveImportCall").withParams(params).execute(context);
	}
	public static void iVK_ScheduledImportActivity_ResetImportTime(IContext context, databasereplication.proxies.ScheduledImportActivity _scheduledImportActivity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ScheduledImportActivity", _scheduledImportActivity == null ? null : _scheduledImportActivity.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ScheduledImportActivity_ResetImportTime").withParams(params).execute(context);
	}
	public static void iVK_ScheduledImportActivity_Save(IContext context, databasereplication.proxies.ScheduledImportActivity _scheduledImportActivity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ScheduledImportActivity", _scheduledImportActivity == null ? null : _scheduledImportActivity.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_ScheduledImportActivity_Save").withParams(params).execute(context);
	}
	public static void iVK_StartImportCall(IContext context, databasereplication.proxies.ImportCall _importCall)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportCall", _importCall == null ? null : _importCall.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_StartImportCall").withParams(params).execute(context);
	}
	public static void iVK_TableMapping_Save(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_TableMapping_Save").withParams(params).execute(context);
	}
	public static void iVK_TableMapping_Update_Save(IContext context, databasereplication.proxies.UpdateConfiguration _updateConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UpdateConfiguration", _updateConfiguration == null ? null : _updateConfiguration.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_TableMapping_Update_Save").withParams(params).execute(context);
	}
	public static void iVK_Template_ConnectMatchingAttributes(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_Template_ConnectMatchingAttributes").withParams(params).execute(context);
	}
	public static void iVK_TM_SaveNext(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_TM_SaveNext").withParams(params).execute(context);
	}
	public static void iVK_TM_Update_SaveNext(IContext context, databasereplication.proxies.UpdateConfiguration _updateConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UpdateConfiguration", _updateConfiguration == null ? null : _updateConfiguration.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_TM_Update_SaveNext").withParams(params).execute(context);
	}
	public static void iVK_UpdateMapping_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseReplication.IVK_UpdateMapping_New").withParams(params).execute(context);
	}
	public static void iVK_XMLDocument_Cancel(IContext context, databasereplication.proxies.XMLDocumentTM _xMLDocumentTM)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("XMLDocumentTM", _xMLDocumentTM == null ? null : _xMLDocumentTM.getMendixObject());
		Core.microflowCall("DatabaseReplication.IVK_XMLDocument_Cancel").withParams(params).execute(context);
	}
	public static void mappingColumn_SetInfo(IContext context, databasereplication.proxies.ColumnMapping _columnMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.MappingColumn_SetInfo").withParams(params).execute(context);
	}
	public static databasereplication.proxies.XMLDocumentTM mB_ExportToXML(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseReplication.MB_ExportToXML").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.XMLDocumentTM.initialize(context, result);
	}
	public static databasereplication.proxies.XMLDocumentTM mB_ExportToXML_UpdateConfig(IContext context, databasereplication.proxies.UpdateConfiguration _updateConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UpdateConfig", _updateConfig == null ? null : _updateConfig.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseReplication.MB_ExportToXML_UpdateConfig").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.XMLDocumentTM.initialize(context, result);
	}
	public static java.util.List<databasereplication.proxies.TableMapping> mB_ImportXMLFile(IContext context, databasereplication.proxies.XMLDocumentTM _xMLDocument, databasereplication.proxies.Database _selectedDatabase)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("XMLDocument", _xMLDocument == null ? null : _xMLDocument.getMendixObject());
		params.put("SelectedDatabase", _selectedDatabase == null ? null : _selectedDatabase.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DatabaseReplication.MB_ImportXMLFile").withParams(params).execute(context);
		java.util.List<databasereplication.proxies.TableMapping> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(databasereplication.proxies.TableMapping.initialize(context, obj));
		}
		return result;
	}
	public static void oC_ConstraintCopyLeftTable(IContext context, databasereplication.proxies.Constraint _constraint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Constraint", _constraint == null ? null : _constraint.getMendixObject());
		Core.microflowCall("DatabaseReplication.OC_ConstraintCopyLeftTable").withParams(params).execute(context);
	}
	public static void oCh_ImportCall_Save(IContext context, databasereplication.proxies.ImportCall _importCall)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportCall", _importCall == null ? null : _importCall.getMendixObject());
		Core.microflowCall("DatabaseReplication.OCh_ImportCall_Save").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_AssociationKey(IContext context, databasereplication.proxies.AssociationKeyOption _isAssociationKey)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("IsAssociationKey", _isAssociationKey == null ? null : _isAssociationKey.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_AssociationKey").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_ConstraintInputObject(IContext context, databasereplication.proxies.ContraintInputObject _constraintInputObject)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ConstraintInputObject", _constraintInputObject == null ? null : _constraintInputObject.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_ConstraintInputObject").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_CustomConstraintType(IContext context, databasereplication.proxies.CustomConstraintType _constraintType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ConstraintType", _constraintType == null ? null : _constraintType.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_CustomConstraintType").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_DatabaseType(IContext context, databasereplication.proxies.DBType _databaseType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseType", _databaseType == null ? null : _databaseType.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_DatabaseType").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_DataHandling(IContext context, databasereplication.proxies.ReferenceDataHandling _dataHandling)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DataHandling", _dataHandling == null ? null : _dataHandling.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_DataHandling").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_ImportAction(IContext context, databasereplication.proxies.ImportAction _importAction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportAction", _importAction == null ? null : _importAction.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_ImportAction").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_JoinType(IContext context, databasereplication.proxies.JoinType _joinType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JoinType", _joinType == null ? null : _joinType.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_JoinType").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_MappingType(IContext context, databasereplication.proxies.MappingType _mappingType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MappingType", _mappingType == null ? null : _mappingType.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_MappingType").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_Mode(IContext context, databasereplication.proxies.Mode _mode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Mode", _mode == null ? null : _mode.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_Mode").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_Operator(IContext context, databasereplication.proxies.Operator _operator)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Operator", _operator == null ? null : _operator.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_Operator").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_QueryType(IContext context, databasereplication.proxies.QueryType _queryType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("QueryType", _queryType == null ? null : _queryType.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_QueryType").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_RefHandling(IContext context, databasereplication.proxies.ReferenceHandlingEnum _handling)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Handling", _handling == null ? null : _handling.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_RefHandling").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_RemoveIndicator(IContext context, databasereplication.proxies.RemoveIndicator _removeIndicator)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RemoveIndicator", _removeIndicator == null ? null : _removeIndicator.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_RemoveIndicator").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_StatisticLevel(IContext context, databasereplication.proxies.StatisticsLevel _printStatisticsMessages)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PrintStatisticsMessages", _printStatisticsMessages == null ? null : _printStatisticsMessages.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_StatisticLevel").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_UpdateConfigurataion(IContext context, databasereplication.proxies.UpdateType _updateType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UpdateType", _updateType == null ? null : _updateType.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_UpdateConfigurataion").withParams(params).execute(context);
	}
	public static java.lang.String parseEnumToString_YesNo(IContext context, databasereplication.proxies.YesNo _useCustomConstraints)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UseCustomConstraints", _useCustomConstraints == null ? null : _useCustomConstraints.name());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ParseEnumToString_YesNo").withParams(params).execute(context);
	}
	public static databasereplication.proxies.AssociationKeyOption parseStringToEnum_AssociationKey(IContext context, java.lang.String _isAssociationKey)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("IsAssociationKey", _isAssociationKey);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_AssociationKey").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.AssociationKeyOption.valueOf(result);
	}
	public static databasereplication.proxies.ContraintInputObject parseStringToEnum_ConstraintInputObject(IContext context, java.lang.String _constraintType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ConstraintType", _constraintType);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_ConstraintInputObject").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.ContraintInputObject.valueOf(result);
	}
	public static databasereplication.proxies.CustomConstraintType parseStringToEnum_CustomConstraintType(IContext context, java.lang.String _constraintType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ConstraintType", _constraintType);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_CustomConstraintType").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.CustomConstraintType.valueOf(result);
	}
	public static databasereplication.proxies.DBType parseStringToEnum_DatabaseType(IContext context, java.lang.String _databaseType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DatabaseType", _databaseType);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_DatabaseType").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.DBType.valueOf(result);
	}
	public static databasereplication.proxies.ReferenceDataHandling parseStringToEnum_DataHandling(IContext context, java.lang.String _dataHandling)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DataHandling", _dataHandling);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_DataHandling").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.ReferenceDataHandling.valueOf(result);
	}
	public static databasereplication.proxies.ImportAction parseStringToEnum_ImportAction(IContext context, java.lang.String _importAction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportAction", _importAction);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_ImportAction").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.ImportAction.valueOf(result);
	}
	public static databasereplication.proxies.JoinType parseStringToEnum_JoinType(IContext context, java.lang.String _joinType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JoinType", _joinType);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_JoinType").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.JoinType.valueOf(result);
	}
	public static databasereplication.proxies.MappingType parseStringToEnum_MappingType(IContext context, java.lang.String _mappingType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MappingType", _mappingType);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_MappingType").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.MappingType.valueOf(result);
	}
	public static databasereplication.proxies.Mode parseStringToEnum_Mode(IContext context, java.lang.String _mode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Mode", _mode);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_Mode").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.Mode.valueOf(result);
	}
	public static databasereplication.proxies.Operator parseStringToEnum_Operator(IContext context, java.lang.String _operator)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Operator", _operator);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_Operator").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.Operator.valueOf(result);
	}
	public static databasereplication.proxies.QueryType parseStringToEnum_QueryType(IContext context, java.lang.String _queryType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("QueryType", _queryType);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_QueryType").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.QueryType.valueOf(result);
	}
	public static databasereplication.proxies.ReferenceHandlingEnum parseStringToEnum_RefHandling(IContext context, java.lang.String _handling)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Handling", _handling);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_RefHandling").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.ReferenceHandlingEnum.valueOf(result);
	}
	public static databasereplication.proxies.RemoveIndicator parseStringToEnum_RemoveIndicator(IContext context, java.lang.String _strRemoveIndicator)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("strRemoveIndicator", _strRemoveIndicator);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_RemoveIndicator").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.RemoveIndicator.valueOf(result);
	}
	public static databasereplication.proxies.StatisticsLevel parseStringToEnum_StatisticsLevel(IContext context, java.lang.String _printStatisticsMessages)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PrintStatisticsMessages", _printStatisticsMessages);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_StatisticsLevel").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.StatisticsLevel.valueOf(result);
	}
	public static databasereplication.proxies.YesNo parseStringToEnum_YesNo(IContext context, java.lang.String _strYesNo)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("strYesNo", _strYesNo);
		java.lang.String result = (java.lang.String) Core.microflowCall("DatabaseReplication.ParseStringToEnum_YesNo").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.YesNo.valueOf(result);
	}
	public static void prepareReferenceHandling(IContext context, databasereplication.proxies.ColumnMapping _pColumn)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("pColumn", _pColumn == null ? null : _pColumn.getMendixObject());
		Core.microflowCall("DatabaseReplication.prepareReferenceHandling").withParams(params).execute(context);
	}
	public static void processActivitySet(IContext context, databasereplication.proxies.ScheduledImportActivity _importActivity, java.util.Date _startDate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportActivity", _importActivity == null ? null : _importActivity.getMendixObject());
		params.put("StartDate", _startDate);
		Core.microflowCall("DatabaseReplication.ProcessActivitySet").withParams(params).execute(context);
	}
	public static java.util.List<databasereplication.proxies.TableMapping> publishedFlow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("DatabaseReplication.PublishedFlow").withParams(params).execute(context);
		java.util.List<databasereplication.proxies.TableMapping> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(databasereplication.proxies.TableMapping.initialize(context, obj));
		}
		return result;
	}
	public static void sE_ImportEverything(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseReplication.SE_ImportEverything").withParams(params).execute(context);
	}
	public static databasereplication.proxies.ColumnMapping sF_DetermineColumnMapping(IContext context, java.util.List<databasereplication.proxies.ColumnMapping> _columnMappingList, databasereplication.proxies.Column _column, databasereplication.proxies.TableMapping _tableMapping, databasereplication.proxies.AdditionalJoins _additionalJoin, mxmodelreflection.proxies.MxObjectMember _mxObjectMember)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_columnMappingList = null;
		if (_columnMappingList != null)
		{
			listparam_columnMappingList = new java.util.ArrayList<>();
			for (databasereplication.proxies.ColumnMapping obj : _columnMappingList)
				listparam_columnMappingList.add(obj.getMendixObject());
		}
		params.put("ColumnMappingList", listparam_columnMappingList);

		params.put("Column", _column == null ? null : _column.getMendixObject());
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		params.put("AdditionalJoin", _additionalJoin == null ? null : _additionalJoin.getMendixObject());
		params.put("MxObjectMember", _mxObjectMember == null ? null : _mxObjectMember.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseReplication.SF_DetermineColumnMapping").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.ColumnMapping.initialize(context, result);
	}
	public static void sF_ImportDatabases_Select(IContext context, databasereplication.proxies.XMLDocumentTM _xMLDocumentTM)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("XMLDocumentTM", _xMLDocumentTM == null ? null : _xMLDocumentTM.getMendixObject());
		Core.microflowCall("DatabaseReplication.SF_ImportDatabases_Select").withParams(params).execute(context);
	}
	public static void sF_MatchAdditionalJoin(IContext context, databasereplication.proxies.AdditionalJoins _additionalJoin, mxmodelreflection.proxies.MxObjectType _mxObjectType, java.util.List<databasereplication.proxies.ColumnMapping> _columnMappingList, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AdditionalJoin", _additionalJoin == null ? null : _additionalJoin.getMendixObject());
		params.put("MxObjectType", _mxObjectType == null ? null : _mxObjectType.getMendixObject());
		java.util.ArrayList<IMendixObject> listparam_columnMappingList = null;
		if (_columnMappingList != null)
		{
			listparam_columnMappingList = new java.util.ArrayList<>();
			for (databasereplication.proxies.ColumnMapping obj : _columnMappingList)
				listparam_columnMappingList.add(obj.getMendixObject());
		}
		params.put("ColumnMappingList", listparam_columnMappingList);

		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.SF_MatchAdditionalJoin").withParams(params).execute(context);
	}
	public static java.lang.String sub_GetLatestErrorMessage(IContext context, system.proxies.Error _error)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Error", _error == null ? null : _error.getMendixObject());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.Sub_GetLatestErrorMessage").withParams(params).execute(context);
	}
	public static databasereplication.proxies.UpdateConfiguration sUB_GetUpdateConfig(IContext context, databasereplication.proxies.TableMapping _tableMapping, java.lang.String _updateType)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		params.put("UpdateType", _updateType);
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseReplication.SUB_GetUpdateConfig").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.UpdateConfiguration.initialize(context, result);
	}
	public static void sUB_SetRefAfterImport_AJ(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.SUB_SetRefAfterImport_AJ").withParams(params).execute(context);
	}
	public static void sUB_SetRefAfterImport_CM(IContext context, databasereplication.proxies.TableMapping _tableMapping, databasereplication.proxies.XMLDocumentTM _xMLDocumentTM)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		params.put("XMLDocumentTM", _xMLDocumentTM == null ? null : _xMLDocumentTM.getMendixObject());
		Core.microflowCall("DatabaseReplication.SUB_SetRefAfterImport_CM").withParams(params).execute(context);
	}
	public static void sUB_SetRefAfterImport_Constraints(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.SUB_SetRefAfterImport_Constraints").withParams(params).execute(context);
	}
	public static void sUB_SetRefAfterImport_RH(IContext context, databasereplication.proxies.TableMapping _tableMapping, databasereplication.proxies.XMLDocumentTM _xMLDocumentTM)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		params.put("XMLDocumentTM", _xMLDocumentTM == null ? null : _xMLDocumentTM.getMendixObject());
		Core.microflowCall("DatabaseReplication.SUB_SetRefAfterImport_RH").withParams(params).execute(context);
	}
	public static void updateColumnTypes(IContext context, databasereplication.proxies.Table _table)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Table", _table == null ? null : _table.getMendixObject());
		Core.microflowCall("DatabaseReplication.UpdateColumnTypes").withParams(params).execute(context);
	}
	public static java.lang.String vA_RetrieveMappingName(IContext context, databasereplication.proxies.ImportCall _importCall)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportCall", _importCall == null ? null : _importCall.getMendixObject());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.VA_RetrieveMappingName").withParams(params).execute(context);
	}
	public static boolean validateColumnMapping(IContext context, databasereplication.proxies.ColumnMapping _columnMapping, databasereplication.proxies.TableMapping _tableMapping, boolean _showFeedback)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ColumnMapping", _columnMapping == null ? null : _columnMapping.getMendixObject());
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		params.put("ShowFeedback", _showFeedback);
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.ValidateColumnMapping").withParams(params).execute(context);
	}
	public static boolean validateDatabase(IContext context, databasereplication.proxies.Database _database)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Database", _database == null ? null : _database.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DatabaseReplication.ValidateDatabase").withParams(params).execute(context);
	}
	public static java.lang.String validateImportActivity(IContext context, databasereplication.proxies.ScheduledImportActivity _scheduledImportActivity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ScheduledImportActivity", _scheduledImportActivity == null ? null : _scheduledImportActivity.getMendixObject());
		return (java.lang.String) Core.microflowCall("DatabaseReplication.ValidateImportActivity").withParams(params).execute(context);
	}
	public static void validateTableMapping(IContext context, databasereplication.proxies.TableMapping _tableMapping)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TableMapping", _tableMapping == null ? null : _tableMapping.getMendixObject());
		Core.microflowCall("DatabaseReplication.ValidateTableMapping").withParams(params).execute(context);
	}
	public static databasereplication.proxies.Table xMLToDom_SearchTable(IContext context, databasereplication.proxies.XMLDocumentTM _xMLMappingParent, java.lang.String _name)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("XMLMappingParent", _xMLMappingParent == null ? null : _xMLMappingParent.getMendixObject());
		params.put("Name", _name);
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseReplication.XMLToDom_SearchTable").withParams(params).execute(context);
		return result == null ? null : databasereplication.proxies.Table.initialize(context, result);
	}
}