// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum AssociationKeyOption
{
	No(new java.lang.String[][] { new java.lang.String[] { "en_US", "No" }, new java.lang.String[] { "nl_NL", "Nee" }, new java.lang.String[] { "en_GB", "No" }, new java.lang.String[] { "en_ZA", "No" } }),
	YesOnlyAssociatedObject(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes, only for the associated object" }, new java.lang.String[] { "nl_NL", "Ja, alleen voor het geassocieerde object" }, new java.lang.String[] { "en_GB", "Yes, only for the associated object" }, new java.lang.String[] { "en_ZA", "Yes, only for the associated object" } }),
	YesOnlyMainObject(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes, only for the main object" }, new java.lang.String[] { "nl_NL", "Ja, alleen voor het hoofd object" }, new java.lang.String[] { "en_GB", "Yes, only for the main object" }, new java.lang.String[] { "en_ZA", "Yes, only for the main object" } }),
	YesMainAndAssociatedObject(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yes, Both for the main object and the associated object" }, new java.lang.String[] { "nl_NL", "Ja, voor het hoofd object en het geassocieerde object" }, new java.lang.String[] { "en_GB", "Yes, Both for the main object and the associated object" }, new java.lang.String[] { "en_ZA", "Yes, Both for the main object and the associated object" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private AssociationKeyOption(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
