// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum ImportAction
{
	Create(new java.lang.String[][] { new java.lang.String[] { "en_US", "Create all objects" }, new java.lang.String[] { "nl_NL", "Maak alles aan" }, new java.lang.String[] { "en_GB", "Create all objects" }, new java.lang.String[] { "en_ZA", "Create all objects" } }),
	Synchronize(new java.lang.String[][] { new java.lang.String[] { "en_US", "Synchronize and create if objects are not found" }, new java.lang.String[] { "nl_NL", "Synchroniseer en creeër wanneer niet gevonden" }, new java.lang.String[] { "en_GB", "Synchronize and create if objects are not found" }, new java.lang.String[] { "en_ZA", "Synchronize and create if objects are not found" } }),
	SynchronizeOnlyExisting(new java.lang.String[][] { new java.lang.String[] { "en_US", "Synchronize only existing objects, ignore others" }, new java.lang.String[] { "nl_NL", "Synchroniseer alleen bestaande objecten, negeer de rest" }, new java.lang.String[] { "en_GB", "Synchronize only existing objects, ignore others" }, new java.lang.String[] { "en_ZA", "Synchronize only existing objects, ignore others" } }),
	OnlyCreateNewObjects(new java.lang.String[][] { new java.lang.String[] { "en_US", "Only create new objects" }, new java.lang.String[] { "nl_NL", "Maak alleen niet bestaande objecten" }, new java.lang.String[] { "en_GB", "Only create new objects" }, new java.lang.String[] { "en_ZA", "Only create new objects" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ImportAction(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
