// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum ReplicationStatusValues
{
	Succesfull(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Succesvol" }, new java.lang.String[] { "en_US", "Succesfull" }, new java.lang.String[] { "en_GB", "Succesfull" }, new java.lang.String[] { "en_ZA", "Succesfull" } }),
	Failed(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Mislukt" }, new java.lang.String[] { "en_US", "Failed" }, new java.lang.String[] { "en_GB", "Failed" }, new java.lang.String[] { "en_ZA", "Failed" } }),
	FailedBeforeConnecting(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Mislukt voor verbinden" }, new java.lang.String[] { "en_US", "Failed before connecting" }, new java.lang.String[] { "en_GB", "Failed before connecting" }, new java.lang.String[] { "en_ZA", "Failed before connecting" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ReplicationStatusValues(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
