// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum UpdateType
{
	AlwaysInsert(new java.lang.String[][] { new java.lang.String[] { "en_US", "Always Insert" }, new java.lang.String[] { "nl_NL", "Altijd een INSERT" }, new java.lang.String[] { "en_GB", "Always Insert" }, new java.lang.String[] { "en_ZA", "Always Insert" } }),
	UpdateOnly(new java.lang.String[][] { new java.lang.String[] { "en_US", "Update Only" }, new java.lang.String[] { "nl_NL", "Alleen Update" }, new java.lang.String[] { "en_GB", "Update Only" }, new java.lang.String[] { "en_ZA", "Update Only" } }),
	UpdateOrInsert(new java.lang.String[][] { new java.lang.String[] { "en_US", "Update Or Insert" }, new java.lang.String[] { "nl_NL", "Update of Insert" }, new java.lang.String[] { "en_GB", "Update Or Insert" }, new java.lang.String[] { "en_ZA", "Update Or Insert" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private UpdateType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
