// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

/**
 * Using this entity you can push the data out to your external database. 
 * 
 * When creating a ReferenceSet from this UpdateSet entity to your own entity, the module will look in those relationships and push all associated entities to the external system.
 */
public class UpdateSet
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject updateSetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseReplication.UpdateSet";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UpdateSet_UpdateConfiguration("DatabaseReplication.UpdateSet_UpdateConfiguration");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UpdateSet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseReplication.UpdateSet"));
	}

	protected UpdateSet(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject updateSetMendixObject)
	{
		if (updateSetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseReplication.UpdateSet", updateSetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseReplication.UpdateSet");

		this.updateSetMendixObject = updateSetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UpdateSet.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databasereplication.proxies.UpdateSet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasereplication.proxies.UpdateSet.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static databasereplication.proxies.UpdateSet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasereplication.proxies.UpdateSet(context, mendixObject);
	}

	public static databasereplication.proxies.UpdateSet load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasereplication.proxies.UpdateSet.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UpdateSet_UpdateConfiguration
	 */
	public final java.util.List<databasereplication.proxies.UpdateConfiguration> getUpdateSet_UpdateConfiguration() throws com.mendix.core.CoreException
	{
		return getUpdateSet_UpdateConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdateSet_UpdateConfiguration
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<databasereplication.proxies.UpdateConfiguration> getUpdateSet_UpdateConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<databasereplication.proxies.UpdateConfiguration> result = new java.util.ArrayList<databasereplication.proxies.UpdateConfiguration>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.UpdateSet_UpdateConfiguration.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(databasereplication.proxies.UpdateConfiguration.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of UpdateSet_UpdateConfiguration
	 * @param updateset_updateconfiguration
	 */
	public final void setUpdateSet_UpdateConfiguration(java.util.List<databasereplication.proxies.UpdateConfiguration> updateset_updateconfiguration)
	{
		setUpdateSet_UpdateConfiguration(getContext(), updateset_updateconfiguration);
	}

	/**
	 * Set value of UpdateSet_UpdateConfiguration
	 * @param context
	 * @param updateset_updateconfiguration
	 */
	public final void setUpdateSet_UpdateConfiguration(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<databasereplication.proxies.UpdateConfiguration> updateset_updateconfiguration)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (databasereplication.proxies.UpdateConfiguration proxyObject : updateset_updateconfiguration)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.UpdateSet_UpdateConfiguration.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return updateSetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasereplication.proxies.UpdateSet that = (databasereplication.proxies.UpdateSet) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseReplication.UpdateSet";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
